### ISSUE TITLE
Please describe "Why" in readme

### ISSUE THREAD

**Issue by leavez** [X140Yu/cocoapods-show-podpsecs-in-project#1]
why should I use this plugin

**Comment by X140Yu** [comment]
Recently I met a problem. 

Xcode 10 does not bundle with `libstdc++6.0.9`, but some pods we depended on write `s.libraries = 'stdc++.6'` in their podspec and cause our project failed to build.  It's pretty frustrating to lookup their podspecs one by one and try to figure out which pod depend on this library. But with this plugin, it's easy to search and locate which extacly cause this problem.

I suppose, this plugin should be only useful at some rate situation.
